# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a10e0299772f55d56f4d8f3ba2442113e8616f1f20b42dabe8146ab890f17bf7b40f76e971755300a285407a6735f5094182cc13f5ae247e8f274c24ff64e823

test:
  secret_key_base: 538b2c8fcab2eef5e37cf560a491be4be7619cd215570697fbc8568ccdbda6450ec9dc0c3ab01e5acc6591cb0f7de3180277832f0fbfc88d0a7299896f985eb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
